export const gameFilterConfig: Record<
  string,
  {
    label: string;
    fields: {
      key: string;
      label: string;
      type: 'select' | 'input' | 'multi-select';
      options?: string[]; // Only for select and multi-select types
      optional?: boolean; // If true, field is optional
    }[];
  }
> = {
  'apex-legends': {
    label: 'Apex Legends',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Rookie',
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Master',
          'Apex Predator',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA-East', 'NA-West', 'EU', 'APAC', 'South America'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Battle Royale', 'Arenas', 'Ranked'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox', 'Switch'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  minecraft: {
    label: 'Minecraft',
    fields: [
      {
        key: 'version',
        label: 'Version',
        type: 'select',
        options: ['1.16', '1.17', '1.18', '1.19', '1.20'],
      },
      {
        key: 'gameMode',
        label: 'Game Mode',
        type: 'multi-select',
        options: ['Survival', 'Creative', 'Adventure'],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'Asia'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['Java', 'Bedrock'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'hardcore', 'modded'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'rocket-league': {
    label: 'Rocket League',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Champion',
          'Grand Champion',
          'Supersonic Legend',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'OCE', 'SAM', 'ASIA'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['1v1', '2v2', '3v3', 'Rumble', 'Hoops', 'Dropshot'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox', 'Switch'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  valorant: {
    label: 'Valorant',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Iron',
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Immortal',
          'Radiant',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'APAC', 'Brazil', 'Korea'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Unrated', 'Competitive', 'Spike Rush', 'Deathmatch'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'league-of-legends': {
    label: 'League of Legends',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Iron',
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Master',
          'Grandmaster',
          'Challenger',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EUW', 'EUNE', 'KR', 'BR', 'LAN', 'LAS', 'OCE'],
      },
      {
        key: 'role',
        label: 'Role',
        type: 'multi-select',
        options: ['Top', 'Jungle', 'Mid', 'ADC', 'Support'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'counter-strike': {
    label: 'Counter-Strike: Global Offensive',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Silver I',
          'Silver II',
          'Silver III',
          'Silver IV',
          'Silver Elite',
          'Silver Elite Master',
          'Gold Nova I',
          'Gold Nova II',
          'Gold Nova III',
          'Gold Nova Master',
          'Master Guardian I',
          'Master Guardian II',
          'Master Guardian Elite',
          'Distinguished Master Guardian',
          'Legendary Eagle',
          'Legendary Eagle Master',
          'Supreme Master First Class',
          'Global Elite',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'Asia'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Competitive', 'Casual', 'Deathmatch'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'dota-2': {
    label: 'Dota 2',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Herald',
          'Guardian',
          'Crusader',
          'Archon',
          'Legend',
          'Ancient',
          'Divine',
          'Immortal',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'SEA', 'China', 'South America'],
      },
      {
        key: 'role',
        label: 'Role',
        type: 'multi-select',
        options: ['Carry', 'Mid', 'Offlane', 'Support'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  fortnite: {
    label: 'Fortnite',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Champion',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA-East', 'NA-West', 'EU', 'Asia', 'Oceania'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Solo', 'Duo', 'Squad'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox', 'Switch'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'call-of-duty-warzone': {
    label: 'Call of Duty: Warzone',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Champion',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA-East', 'NA-West', 'EU', 'Asia', 'Oceania'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Battle Royale', 'Plunder'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'overwatch-2': {
    label: 'Overwatch 2',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Diamond',
          'Master',
          'Grandmaster',
          'Top 500',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'APAC', 'South America'],
      },
      {
        key: 'role',
        label: 'Role',
        type: 'multi-select',
        options: ['Tank', 'Damage', 'Support'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  fifa: {
    label: 'FIFA',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Diamond'],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'Asia'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Ultimate Team', 'Career Mode', 'Pro Clubs'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Ranked'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'world-of-warcraft': {
    label: 'World of Warcraft',
    fields: [
      {
        key: 'class',
        label: 'Class',
        type: 'select',
        options: [
          'Druid',
          'Hunter',
          'Mage',
          'Paladin',
          'Priest',
          'Rogue',
          'Shaman',
          'Warlock',
          'Warrior',
          'Death Knight',
          'Monk',
          'Demon Hunter',
          'Evoker',
        ],
      },
      {
        key: 'spec',
        label: 'Specialization',
        type: 'select',
        options: [
          'Balance',
          'Feral',
          'Guardian',
          'Restoration',
          'Beast Mastery',
          'Marksmanship',
          'Survival',
          'Arcane',
          'Fire',
          'Frost',
          'Holy',
          'Protection',
          'Retribution',
          'Discipline',
          'Shadow',
          'Assassination',
          'Outlaw',
          'Subtlety',
          'Elemental',
          'Enhancement',
          'Restoration Shaman',
          'Affliction Warlock',
          'Demonology Warlock',
          'Destruction Warlock',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'Asia'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'Raid', 'Dungeon', 'PvP', 'Mythic+', 'Quests'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'genshin-impact': {
    label: 'Genshin Impact',
    fields: [
      {
        key: 'adventureRank',
        label: 'Adventure Rank',
        type: 'select',
        options: ['1-20', '21-40', '41-50', '51-60'],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['Mondstadt', 'Liyue', 'Inazuma', 'Sumeru'],
      },
      {
        key: 'gameType',
        label: 'Game Type',
        type: 'multi-select',
        options: ['Casual', 'co-op', 'exploration'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'team-fortress-2': {
    label: 'Team Fortress 2',
    fields: [
      {
        key: 'class',
        label: 'Class',
        type: 'select',
        options: [
          'Scout',
          'Soldier',
          'Pyro',
          'Demoman',
          'Heavy',
          'Engineer',
          'Medic',
          'Sniper',
          'Spy',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'Asia'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Casual', 'Competitive', 'Mann vs. Machine'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
  'rainbow-six-siege': {
    label: 'Rainbow Six Siege',
    fields: [
      {
        key: 'rank',
        label: 'Rank',
        type: 'select',
        options: [
          'Copper',
          'Bronze',
          'Silver',
          'Gold',
          'Platinum',
          'Emerald',
          'Diamond',
          'Champion',
        ],
      },
      {
        key: 'region',
        label: 'Region',
        type: 'select',
        options: ['NA', 'EU', 'APAC', 'South America'],
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'multi-select',
        options: ['Casual', 'Ranked', 'UnRanked'],
      },
      {
        key: 'platform',
        label: 'Platform',
        type: 'select',
        options: ['PC', 'PlayStation', 'Xbox'],
      },
      {
        key: 'optionalNote',
        label: 'Optional Note',
        type: 'input',
        optional: true,
      },
    ],
  },
};
